# Generated by Django 3.2.3 on 2022-06-18 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bn', '0002_alter_donnausers_username_alter_guestusers_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=132131)),
                ('balance', models.FloatField()),
            ],
        ),
        migrations.AlterField(
            model_name='donnausers',
            name='username',
            field=models.CharField(max_length=100000),
        ),
        migrations.AlterField(
            model_name='guestusers',
            name='username',
            field=models.CharField(max_length=100000),
        ),
    ]
