# Generated by Django 4.0.5 on 2023-04-04 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bn', '0006_remove_balance_balance_remove_balance_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='balance',
            name='close_order',
            field=models.CharField(default='empty', max_length=232323),
        ),
        migrations.AddField(
            model_name='balance',
            name='close_position',
            field=models.CharField(default='empty', max_length=232323),
        ),
    ]
