# Generated by Django 4.0.5 on 2023-04-27 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bn', '0008_guestusers_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bybit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(default='empty', max_length=232323)),
                ('leverage', models.IntegerField(default=0)),
                ('side', models.CharField(default='empty', max_length=232323)),
                ('entry_price', models.FloatField(default=0)),
                ('tp1', models.FloatField(default=0)),
                ('tp2', models.FloatField(default=0)),
                ('tp3', models.FloatField(default=0)),
                ('tp4', models.FloatField(default=0)),
                ('tp5', models.FloatField(default=0)),
                ('tp6', models.FloatField(default=0)),
                ('stop_loss', models.FloatField(default=0)),
                ('close_order', models.CharField(default='empty', max_length=232323)),
                ('close_position', models.CharField(default='empty', max_length=232323)),
            ],
        ),
    ]
